// frontend/src/routes/institutions/$institutionId/courses/$courseId/_layout/discussion.tsx
// import { MessageSquareIcon } from "lucide-react";
import { Separator } from "@/components/ui/separator";
import { createFileRoute, Link, Outlet } from "@tanstack/react-router";
import { Card, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { BASE_URL } from "@/lib/constants";
import { CourseThread } from "@/lib/types";
import { buttonVariants } from "@/components/ui/button";
import { PlusIcon } from "lucide-react";
import { Input } from "@/components/ui/input";

async function fetchCourseDiscussions(courseId: string) {
  const response = await fetch(`${BASE_URL}/app/courses/${courseId}/threads`, {
    method: "GET",
    credentials: "include",
  });
  const threads = (await response.json()) as CourseThread[];
  return threads;
}

export const Route = createFileRoute(
  "/institutions/$institutionId/courses/$courseId/_layout/discussion"
)({
  loader: ({ params }) => fetchCourseDiscussions(params.courseId),
  component: Discussion,
});

function Discussion() {
  const { institutionId, courseId } = Route.useParams();

  const courseThreads = Route.useLoaderData() as CourseThread[];

  return (
    <div className="flex flex-grow">
      <div className="flex flex-col">
        <div className="p-2 border-b">
          <Input
            type="text"
            placeholder="Search threads..."
            className="w-full"
          />
        </div>
        <div className="gap-2 p-2 flex flex-col w-64 lg:w-72">
          <Link
            to="/institutions/$institutionId/courses/$courseId/discussion/new"
            className={`${buttonVariants({ variant: "default" })} w-full h-12`}
            params={{ institutionId, courseId }}
          >
            New Thread <PlusIcon />
          </Link>
          {courseThreads?.map((thread) => (
            <Link
              key={thread.id}
              to="/institutions/$institutionId/courses/$courseId/discussion/$threadId"
              params={{
                institutionId,
                courseId,
                threadId: thread.id.toString(),
              }}
            >
              <Card>
                <CardHeader>
                  <CardTitle>{thread.title}</CardTitle>
                </CardHeader>
                <CardFooter className="flex justify-between">
                  {new Date(thread.createdAt).toLocaleDateString()}
                </CardFooter>
              </Card>
            </Link>
          ))}
        </div>
      </div>
      <Separator orientation="vertical" />
      {/* Thread */}
      <div className="flex flex-grow p-8">
        <Outlet />
      </div>
      {/* <div className="flex flex-grow justify-center items-center">
          <div className="flex flex-col items-center gap-4">
            <MessageSquareIcon size={64} />
            <span className="text-xl font-bold">Select a thread</span>
          </div>
        </div> */}
    </div>
  );
}

// src/routes/subjects/[subjectId]/discussion/+page.svelte
<script lang="ts">
	import Button, { buttonVariants } from '$lib/components/ui/button/button.svelte';
	import * as Card from '$lib/components/ui/card';
	import PlusIcon from '@lucide/svelte/icons/plus';

	let { data } = $props();
</script>

<div class="mb-3 flex items-center justify-between">
	<h1 class="mb-4 text-3xl font-bold">Discussion</h1>
	<a href="/subjects/{data.subjectIdInt}/discussion/new" class={buttonVariants()}
		>New Post <PlusIcon /></a
	>
</div>

{#if data?.threads}
	<div class="space-y-4">
		{#each data.threads as thread}
			<Card.Root>
				<Card.Header>
					<Card.Title>{thread.title}</Card.Title>
					<Card.Description>{thread.userId}</Card.Description>
				</Card.Header>
				<Card.Content>
					{thread.content}
				</Card.Content>
				<Card.Footer>
					<span>Created {new Date(thread.createdAt).toLocaleDateString()}</span>
				</Card.Footer>
			</Card.Root>
		{/each}
	</div>
{:else}
	<p>No discussion posts available.</p>
{/if}
