// frontend/src/routes/login.tsx
import { createFileRoute, redirect, useNavigate } from "@tanstack/react-router";
import { useForm } from "react-hook-form";

import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { useAuthStore } from "@/lib/auth";
import { BASE_URL, KEY_LS_USER } from "@/lib/constants";
import { User } from "@/lib/types";

export type LoginType = {
  username: string;
  password: string;
};

export const Route = createFileRoute("/login")({
  beforeLoad: () => {
    const isLoggedIn = useAuthStore.getState().user;
    if (isLoggedIn) {
      throw redirect({
        to: "/dashboard",
      });
    }
  },
  component: Login,
});

function Login() {
  const navigate = useNavigate();
  const setUser = useAuthStore((state) => state.setUser);

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<LoginType>();

  const onSubmit = async (data: LoginType) => {
    try {
      const response = await fetch(`${BASE_URL}/auth/login`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(data),
        credentials: "include",
      });

      if (response.ok) {
        const user = (await response.json()) as User | null;
        setUser(user);
        localStorage.setItem(KEY_LS_USER, JSON.stringify(user));
        navigate({
          to: "/dashboard",
        });
      }
    } catch (error) {
      console.error("Login failed:", error);
    }
  };

  return (
    <div className="flex justify-center items-center w-full h-full">
      <Card className="max-w-md">
        <CardHeader className="space-y-1">
          <CardTitle className="text-2xl font-bold">Login</CardTitle>
          <CardDescription>
            Enter your username and password to login to your account
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="username">Username</Label>
              <Input
                id="username"
                type="text"
                autoComplete="username"
                {...register("username", { required: "Username is required" })}
              />
              {errors.username && (
                <p className="text-red-600">{errors.username.message}</p>
              )}
            </div>
            <div className="space-y-2">
              <Label htmlFor="password">Password</Label>
              <Input
                id="password"
                type="password"
                autoComplete="current-password"
                {...register("password", { required: "Password is required" })}
              />
              {errors.password && (
                <p className="text-red-600">{errors.password.message}</p>
              )}
            </div>
            <Button type="submit" className="w-full">
              Login
            </Button>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}

// src/routes/auth/login/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import Button from '$lib/components/ui/button/button.svelte';
	import Input from '$lib/components/ui/input/input.svelte';
	let { form } = $props();
</script>

<div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
	<div class="sm:mx-auto sm:w-full sm:max-w-sm">
		<h2 class="text-center text-2xl/9 font-bold tracking-tight">Sign in to your account</h2>
	</div>
	<div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
		<form class="space-y-6" method="post" action="?/login" use:enhance>
			<div>
				<label for="email" class="block text-sm/6 font-medium">Email address</label>
				<div class="mt-2">
					<Input
						type="email"
						name="email"
						id="email"
						autocomplete="email"
						required
						class="input w-full"
					/>
				</div>
			</div>

			<div class="space-y-2">
				<label for="password" class="block text-sm/6 font-medium">Password</label>
				<div class="mt-2">
					<Input
						type="password"
						name="password"
						id="password"
						autocomplete="current-password"
						required
						class="input w-full"
					/>
				</div>
				<div class="text-right text-sm">
					<a href="forgot-password" class="text-primary font-semibold">Forgot password?</a>
				</div>
			</div>

			<Button type="submit">Sign in</Button>
		</form>
	</div>

	<p style="color: red">{form?.message ?? ''}</p>
</div>
